trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - develop
  paths:
    exclude:
      - README.md
      - LICENSE
pr: none
  
jobs:
  - job: RouterDockerImages

    timeoutInMinutes: 240
  
    strategy:
      matrix:
        amd64:
          poolImageName: 'Azure Pipelines'
          imageTagSuffix: 'amd64'
        arm32v7:
          poolImageName: 'RPi'
          imageTagSuffix: 'arm32v7'
        arm64v8:
          poolImageName: 'build-farm-coral'
          imageTagSuffix: 'arm64v8'

    pool: $(poolImageName)

    variables:
      imageName: 'gcr.io/focal-freedom-236620/router'
      imageTag: 'dev'
      ref: $(Build.SourceBranch)
      buildTag: $(Build.BuildId)

    steps:
      - script: |
          if [[ $(ref) == refs/tags* ]]; then
            TAG=$(echo $(ref) | sed "s|refs/tags/v||g")
            echo "##vso[task.setvariable variable=imageTag]$TAG"
          else
            LATESTTAG=$(git tag | tail -1)
            LATESTVERS=${LATESTTAG#?}
            if [ -z "$LATESTVERS" ]; then LATESTVERS=0.0.0; fi
            echo "##vso[task.setvariable variable=imageTag]$LATESTVERS-b$(buildTag)"
          fi
        displayName: 'Set image tag'

      - template: ./pipeline.yaml
        parameters:
          imageName: $(imageName)
          imageTag: $(imageTag)-$(imageTagSuffix)
          dockerFile: 'Dockerfile'
  
  - job: ioFogRouterDockerManifest
    dependsOn: RouterDockerImages

    timeoutInMinutes: 240
  
    pool: 'Azure Pipelines'

    variables:
      imageName: 'gcr.io/focal-freedom-236620/router'
      imageTag: 'dev'
      ref: $(Build.SourceBranch)
      buildTag: $(Build.BuildId)
      DOCKER_CLI_EXPERIMENTAL: enabled

    steps:
      - script: |
          if [[ $(ref) == refs/tags* ]]; then
            TAG=$(echo $(ref) | sed "s|refs/tags/v||g")
            echo "##vso[task.setvariable variable=imageTag]$TAG"
          else
            LATESTTAG=$(git tag | tail -1)
            LATESTVERS=${LATESTTAG#?}
            if [ -z "$LATESTVERS" ]; then LATESTVERS=0.0.0; fi
            echo "##vso[task.setvariable variable=imageTag]$LATESTVERS-b$(buildTag)"
          fi
        displayName: 'Set image tag'

      - task: Docker@2
        displayName: Login to Dockerhub
        inputs:
          command: login
          containerRegistry: 'Edgeworx GCP'

      - script: |
          docker pull $(imageName):$(imageTag)-amd64
          docker pull $(imageName):$(imageTag)-arm32v7
          docker pull $(imageName):$(imageTag)-arm64v8
        displayName: 'Pull amd64, arm32v7, and arm64v8 docker images'

      - script: |
          docker manifest create \
            $(imageName):$(imageTag) \
            --amend $(imageName):$(imageTag)-amd64 \
            --amend $(imageName):$(imageTag)-arm32v7 \
            --amend $(imageName):$(imageTag)-arm64v8
        displayName: 'Create image manifest'

      - script: |
          docker manifest push $(imageName):$(imageTag)
        displayName: 'Push image manifest'
