parameters:
  - name: imageName
    type: string
  - name: imageTag
    type: string
  - name: dockerFile
    type: string

steps:
  - task: Docker@2
    displayName: Build and push image
    inputs:
      containerRegistry: 'Edgeworx GCP'
      repository: ${{ parameters.imageName }}
      command: buildAndPush
      Dockerfile: ${{ parameters.dockerFile }}
      tags: |
        ${{ parameters.imageTag }}
      arguments: --build-arg BASE_IMAGE_TAG=${{ parameters.imageTag }}
